### ISSUE TITLE
Tiny suggestion to emphasise what the severity levels mean

### ISSUE THREAD

**Issue by danielmmmm** [RaffBenato/funcap55#1]
This is a very well made test. I love that the scoring key is always kept at the top of the screen.

It would be helpful to add a description of the severity grades directly into graph-md-en.png. I know it's in the description below ... but some people see the graph and miss the text ;-)

The point is to emphasise that even "mild ME" is a debilitating condition. It is especially important to educate politicians, employers, and friends/family. These are groups who might not be compassionate to people with a "mild" condition. But also ME patients would benefit because it gives them the means to express themselves and advocate for themselves (e.g. saying "vastly lowered activity level" instead of just "mild").
Obviously, there has to be a nomenclature for the severity levels of illnesses. But we should either find an alternative to "mild", or explain what it means (without diminishing what more severe patients experience).

Sorry for the bad mock-up :-)
![scale](https://github.com/RaffBenato/funcap55/assets/3389179/cc8b6a75-ba32-45b6-ae48-2a2104c250d2)

**Comment by RaffBenato** [comment]
Thank you for the suggestion, I have updated the graph image.

**Comment by danielmmmm** [comment]
Much appreciated! 😊💖
